### ISSUE TITLE
PropTypes warnings from Pager

### ISSUE THREAD

**Issue by jochenberger** [eddyson-de/react-grid#216]
If I add a `<Pager rowsPerPage={10} />` to my Grid, I get warnings that `currentPage`, `numberOfPages`, and `onChange` are required.

**Comment by karissame** [comment]
Same here. What is the workaround for now?

**Comment by fkretzer** [comment]
For the 1.0-alpha we implemented the new API on top of the old code. Therefore some warnings are unavoidable. We are currently in the process of refactoring the internals to better match the new API. When we reach a 1.0, release there should be no warnings at all :-)

TLDR; If you want a more stable experience, please use the latest 0.x release (currently 0.8.6) in the meantime. 
It has all customisation features available through the old "nested object configuration"-approach. Drop us a line if you need some assistance. Unfortunately there is no documentation besides the jsfiddle at this point :-(

**Comment by fkretzer** [comment]
Now obsolete due to the new API. To set the page size, just use the `defaultPageSize`-prop. Should work in the next alpha-release.
