### ISSUE TITLE
Replace `hideTools` prop

### ISSUE THREAD

**Issue by jochenberger** [eddyson-de/react-grid#499]
The prop is awkwardly named, because it only hides the filter.
Also, I'm not sure whether it should remain a prop of the `Column` component, e.g. `filterable={false}`. It's similar to `sortable`, but we might also argue that it should be `<Column ...><Filter hide /></Column>`.

**Comment by fkretzer** [comment]
I would prefer <Column ...><Filter hide /></Column> as this more consistent with the declarative 1.0 API
