### ISSUE TITLE
Using absurd values for `paging` should throw an exception.

### ISSUE THREAD

**Issue by sboekhoff** [eddyson-de/react-grid#57]
When setting `paging` to absurd values (i.e. `<= 0` of Strings) an exception should be thrown.

**When using `0`**, currently a non-functional pagination is shown, having `Infinity` as last value:

![grid1](https://cloud.githubusercontent.com/assets/10683690/16650341/edc5f61e-443d-11e6-8d26-60740b714d77.png)

(see https://jsfiddle.net/boekhoff/j71pjqqa/1/)

**When using a negative value**, currently no pagination is shown. Moreover the number of entries shown is reduced by the value used for `paging`. Example: Having an array of four entries and using `paging: -2` results in a list with 2 entries being displayed:
![grid2](https://cloud.githubusercontent.com/assets/10683690/16650743/1a2b5b5c-4440-11e6-90d9-4c9d4d86fc0e.png)

(see https://jsfiddle.net/boekhoff/j71pjqqa/)

**When using a string**, currently a pagination with a single page and no entries is shown.

![grid3](https://cloud.githubusercontent.com/assets/10683690/16650766/3aa8e462-4440-11e6-851a-1c4fe6389983.png)

(see https://jsfiddle.net/boekhoff/j71pjqqa/2/)

**Comment by jochenberger** [comment]
The `string` case is caught and properly reported, have a look into the console: 
```
Warning: Failed prop type: Invalid prop `paging` of type `string` supplied to `Pager`, expected `number`.
```

**Comment by sboekhoff** [comment]
@jochenberger : you're right (I didn't check that).

But is the pagination with `1 | ... ` the right thing being displayed?

![grid5](https://cloud.githubusercontent.com/assets/10683690/16651229/eddb6f4e-4442-11e6-9722-090df352e798.png)

I'd expect an empty pagination:

![grid4](https://cloud.githubusercontent.com/assets/10683690/16651224/e50d081e-4442-11e6-8cec-9a974b85fee7.png)

**Comment by jochenberger** [comment]
IMO there is no correct reaction to invalid prop types. That's what the warnings are for.
