### ISSUE TITLE
Show 'no entry to be displayed'-message if list is empty.

### ISSUE THREAD

**Issue by sboekhoff** [eddyson-de/react-grid#59]
As a user: if either the list of objects to be displayed is empty or non of the values from the list matches the filter criteria, I'd like to be informed.

**If the list is empty**, currently only arrows of the navigation are displayed.

![grid6](https://cloud.githubusercontent.com/assets/10683690/16651780/7b94cbca-4446-11e6-86fd-0700846ab969.png)

(See: https://jsfiddle.net/boekhoff/j71pjqqa/4/)

**If the criterion / the criteria exclude(s) all entries**, nothing follows the toolbar:

![grid7](https://cloud.githubusercontent.com/assets/10683690/16651809/b8bd75e2-4446-11e6-91c9-979599bbe8d3.png)

In both cases I'd expect a message like `No data to be displayed` or `No entries matching the criteria`

**Comment by jochenberger** [comment]
See also #55

**Comment by jochenberger** [comment]
We should make the actual content configurable, probably allow `PropTypes.node` or `PropTypes.func`.
If we know which columns we are going to render (i.e. if `showColumnsWithoutConfig` is `false`), we could also render the whole table with the message inside a `td` that spans a whole row.
