### ISSUE TITLE
Updating props resets paging and sorting

### ISSUE THREAD

**Issue by jochenberger** [eddyson-de/react-grid#9]
In the `Grid` component, the paging and sorting states are reset in `componentWillReceiveProps`. I think that this behavior is confusing. But it might not be a good idea to always retain the state either.
Maybe we should check if the prop has changed in nextProps and only update the state if it has?

**Comment by jochenberger** [comment]
This would work for sorting only, because `skip` is not passed in as a prop.

**Comment by jochenberger** [comment]
As to the paging, I think that just removing the `skip: 0` from the `setState` call in `Grid`'s `componentWillReceiveProps` should make the behavior more intuitive. I'll create a PR.

**Comment by jochenberger** [comment]
See also #28.

**Comment by fkretzer** [comment]
I think #28 should fix this. Once we have documentation, we should mention that there is always the option to use the stateless internal component (Àrdagryd`) if more customisation is necessary.
